export const SECTIONS = {
  about: {
    title: 'About',
    background: '#0045FF',
    color: '#F2F2F2',
    logoBackground: '#F2F2F2',
    icon: 'main/about.svg',
    gradientColors: ['#3CDBA2', 'rgba(60, 219, 162, 1)'],
    size: 6,
    className: 'about',
  },
  projects: {
    title: 'Projects',
    logoBackground: '#F2F2F2',
    background: '#202020',
    icon: 'main/projects.svg',
    gradientColors: ['#3CDBA2', 'rgba(60, 219, 162, 1)'],
    size: 2,
    className: 'projects',
  },
  contact: {
    title: 'Contact me',
    logoBackground: '#202020',
    color: '#1E1E1E',
    background: '#EDEDED',
    icon: 'main/contact.svg',
    gradientColors: ['#3CDBA2', 'rgba(60, 219, 162, 1)'],
    size: 2,
    className: 'contact',
  },
  experience: {
    title: 'Experience',
    logoBackground: '#202020',
    background: '#3CDBA2',
    color: '#1E1E1E',
    icon: 'main/experience.svg',
    gradientColors: ['#0045FF', 'rgba(60, 219, 162, 1)'],
    size: 2,
    className: 'experience',
  },
  blog: {
    title: 'Blog',
    logoBackground: '#F2F2F2',
    background: '#0045FF',
    icon: 'main/blog.svg',
    gradientColors: ['#3CDBA2', 'rgba(60, 219, 162, 1)'],
    size: 2,
    className: 'blog',
  },
};
